// src/lib/components/Projects.svelte
<script lang="ts">
  import { projectsData } from "$lib/data";
  import Project from "./Project.svelte";
  import SectionHeading from "./SectionHeading.svelte";
  import SectionSpy from "./SectionSpy.svelte";
</script>

<SectionSpy
  section="Projects"
  id="projects"
  label="Projects"
  class="mb-28 w-full max-w-2xl scroll-mt-28 outline-none"
>
  <SectionHeading>My projects</SectionHeading>
  <div>
    {#each projectsData as project (project.title)}
      <Project {...project} />
    {/each}
  </div>
</SectionSpy>

// components/projects.tsx
"use client";

import SectionHeading from "./section-heading";
import Project from "./project";
import { projectsData } from "@/lib/data";
import { useSectionInView } from "@/lib/hooks";

export default function Projects() {
  const { ref } = useSectionInView("Projects");

  return (
    <section
      ref={ref}
      id="projects"
      tabIndex={-1}
      aria-label="Projects"
      className="mb-28 w-full max-w-2xl scroll-mt-28 outline-none"
    >
      <SectionHeading>My projects</SectionHeading>
      <div>
        {projectsData.map((project) => (
          <Project key={project.title} {...project} />
        ))}
      </div>
    </section>
  );
}
