// components/contact.tsx
"use client";

import { useActionState, useState } from "react";
import { m } from "motion/react";
import { track } from "@vercel/analytics";
import toast from "react-hot-toast";

import SectionHeading from "./section-heading";
import SubmitBtn from "./submit-btn";
import { useSectionInView } from "@/lib/hooks";
import { sendEmail } from "@/actions/sendEmail";
import { emailId, EMAIL_MAX_LENGTH, MESSAGE_MAX_LENGTH } from "@/lib/data";

type FormState = { error?: string; success?: boolean } | null;

export default function Contact() {
  const { ref } = useSectionInView("Contact");
  // Controlled so a failed submit keeps what the user typed (React 19 resets
  // uncontrolled form actions), and we clear them only on success.
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");

  const [state, formAction] = useActionState<FormState, FormData>(
    async (_prev, formData) => {
      const { error } = await sendEmail(formData);
      if (error) {
        toast.error(error);
        return { error };
      }
      toast.success("Email sent successfully!");
      track("contact_submit");
      setEmail("");
      setMessage("");
      return { success: true };
    },
    null,
  );

  return (
    <m.section
      id="contact"
      ref={ref}
      tabIndex={-1}
      aria-label="Contact"
      className="mb-20 sm:mb-28 w-[min(100%,38rem)] text-center outline-none scroll-mt-28"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 1 }}
      viewport={{ once: true }}
    >
      <SectionHeading>Contact me</SectionHeading>

      <p className="text-gray-700 -mt-6 dark:text-white/80">
        Have a role, a project, or just want to say hi? Drop me a line below, or
        email me directly at{" "}
        <a className="underline" href={`mailto:${emailId}`}>
          {emailId}
        </a>
        .
      </p>

      <form className="mt-10 flex flex-col dark:text-black" action={formAction}>
        {/* Honeypot: hidden from real users; spam bots fill it and get
            silently dropped server-side. A non-semantic name + ignore hints
            keep browsers/password managers from autofilling it (which would
            wrongly drop a legitimate message). */}
        <input
          type="text"
          name="contact_reason_hp"
          tabIndex={-1}
          autoComplete="off"
          aria-hidden="true"
          data-1p-ignore="true"
          data-lpignore="true"
          className="absolute left-[-9999px] h-0 w-0 overflow-hidden"
        />
        <label htmlFor="senderEmail" className="sr-only">
          Your email
        </label>
        <input
          id="senderEmail"
          name="senderEmail"
          type="email"
          required
          maxLength={EMAIL_MAX_LENGTH}
          autoComplete="email"
          placeholder="Your email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          aria-invalid={state?.error ? true : undefined}
          aria-describedby={state?.error ? "contact-error" : undefined}
          className="h-14 px-4 rounded-lg borderBlack outline-none transition-all focus-ring dark:bg-white/80 dark:focus:bg-white"
        />
        <label htmlFor="message" className="sr-only">
          Your message
        </label>
        <textarea
          id="message"
          name="message"
          required
          maxLength={MESSAGE_MAX_LENGTH}
          placeholder="Your message"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyDown={(e) => {
            // Cmd/Ctrl+Enter submits; plain Enter stays a newline.
            if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
              e.currentTarget.form?.requestSubmit();
            }
          }}
          aria-invalid={state?.error ? true : undefined}
          aria-describedby={state?.error ? "contact-error" : undefined}
          className="h-52 my-3 resize-y rounded-lg borderBlack p-4 outline-none transition-all focus-ring dark:bg-white/80 dark:focus:bg-white"
        />
        <SubmitBtn />

        {state?.error && (
          <p
            id="contact-error"
            role="alert"
            className="mt-3 text-sm text-red-600 dark:text-red-400"
          >
            {state.error}
          </p>
        )}
      </form>
    </m.section>
  );
}

// src/lib/components/Contact.svelte
<script lang="ts">
  import { track } from "$lib/analytics";
  import { reveal } from "$lib/actions/reveal";
  import { sectionSpy } from "$lib/actions/section-spy";
  import { emailId, EMAIL_MAX_LENGTH, MESSAGE_MAX_LENGTH } from "$lib/data";
  import { toast } from "$lib/state/toast.svelte";
  import type { SendEmailResult } from "$lib/types";
  import SectionHeading from "./SectionHeading.svelte";
  import SubmitBtn from "./SubmitBtn.svelte";
  import Turnstile from "./Turnstile.svelte";

  let email = $state("");
  let message = $state("");
  let pending = $state(false);
  let error = $state<string | null>(null);
  let turnstileToken = $state<string | null>(null);

  let turnstile = $state<ReturnType<typeof Turnstile> | null>(null);
  let form = $state<HTMLFormElement | null>(null);

  /** Boot Turnstile on first contact with the form, not on page load. */
  function warmUpChallenge() {
    turnstile?.start();
  }

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (pending || !form) return;

    pending = true;
    error = null;

    try {
      const body = new FormData(form);
      if (turnstileToken) body.set("cf-turnstile-response", turnstileToken);

      const response = await fetch("/api/contact", {
        method: "POST",
        body,
      });
      const result = (await response.json()) as SendEmailResult;

      if (result.error) {
        error = result.error;
        toast.error(result.error);
        return;
      }

      toast.success("Email sent successfully!");
      track("contact_submit");
      // Cleared only on success, so a failed submit keeps what was typed.
      email = "";
      message = "";
    } catch {
      const failure = "Couldn't send your message. Please try again later.";
      error = failure;
      toast.error(failure);
    } finally {
      pending = false;
    }
  }

  function onMessageKeydown(event: KeyboardEvent) {
    // Cmd/Ctrl+Enter submits; plain Enter stays a newline.
    if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
      event.preventDefault();
      form?.requestSubmit();
    }
  }
</script>

<section
  id="contact"
  tabindex="-1"
  aria-label="Contact"
  data-reveal
  use:sectionSpy={"Contact"}
  use:reveal={{ amount: 0.1 }}
  class="mb-20 w-[min(100%,38rem)] scroll-mt-28 text-center outline-none sm:mb-28"
>
  <SectionHeading>Contact me</SectionHeading>

  <p class="-mt-6 text-gray-700 dark:text-white/80">
    Have a role, a project, or just want to say hi? Drop me a line below, or
    email me directly at
    <a class="underline" href="mailto:{emailId}">{emailId}</a>.
  </p>

  <form
    bind:this={form}
    onsubmit={handleSubmit}
    onfocusin={warmUpChallenge}
    class="mt-10 flex flex-col dark:text-black"
  >
    <!--
      Honeypot: hidden from real users; spam bots fill it and get silently
      dropped server-side. A non-semantic name + ignore hints keep browsers and
      password managers from autofilling it (which would wrongly drop a
      legitimate message). Kept alongside Turnstile because it costs nothing and
      catches the naive form-fillers before a challenge is ever evaluated.
    -->
    <input
      type="text"
      name="contact_reason_hp"
      tabindex="-1"
      autocomplete="off"
      aria-hidden="true"
      data-1p-ignore="true"
      data-lpignore="true"
      class="absolute left-[-9999px] h-0 w-0 overflow-hidden"
    />

    <label for="senderEmail" class="sr-only">Your email</label>
    <input
      id="senderEmail"
      name="senderEmail"
      type="email"
      required
      maxlength={EMAIL_MAX_LENGTH}
      autocomplete="email"
      placeholder="Your email"
      bind:value={email}
      aria-invalid={error ? "true" : undefined}
      aria-describedby={error ? "contact-error" : undefined}
      class="focus-ring borderBlack h-14 rounded-lg px-4 outline-none transition-all dark:bg-white/80 dark:focus:bg-white"
    />

    <label for="message" class="sr-only">Your message</label>
    <textarea
      id="message"
      name="message"
      required
      maxlength={MESSAGE_MAX_LENGTH}
      placeholder="Your message"
      bind:value={message}
      onkeydown={onMessageKeydown}
      aria-invalid={error ? "true" : undefined}
      aria-describedby={error ? "contact-error" : undefined}
      class="focus-ring borderBlack my-3 h-52 resize-y rounded-lg p-4 outline-none transition-all dark:bg-white/80 dark:focus:bg-white"
    ></textarea>

    <Turnstile bind:this={turnstile} onToken={(t) => (turnstileToken = t)} />

    <div class="mt-3 flex justify-center">
      <SubmitBtn {pending} />
    </div>

    {#if error}
      <p
        id="contact-error"
        role="alert"
        class="mt-3 text-sm text-red-600 dark:text-red-400"
      >
        {error}
      </p>
    {/if}
  </form>
</section>
