// components/experience.tsx
import SectionHeading from "./section-heading";
import ExperienceTimeline from "./experience-timeline";
import SectionSpy from "./section-spy";

// Server component: the timeline is static markup, so nothing below
// SectionSpy reaches the client bundle.
export default function Experience() {
  return (
    <SectionSpy
      section="Experience"
      id="experience"
      aria-label="Experience and education"
      className="scroll-mt-28 mb-28 outline-none sm:mb-40"
    >
      <SectionHeading>My experience</SectionHeading>
      <ExperienceTimeline />
    </SectionSpy>
  );
}

// src/lib/components/Experience.svelte
<script lang="ts">
  import ExperienceTimeline from "./ExperienceTimeline.svelte";
  import SectionHeading from "./SectionHeading.svelte";
  import SectionSpy from "./SectionSpy.svelte";
</script>

<SectionSpy
  section="Experience"
  id="experience"
  label="Experience and education"
  class="mb-28 scroll-mt-28 outline-none sm:mb-40"
>
  <SectionHeading>My experience</SectionHeading>
  <ExperienceTimeline />
</SectionSpy>
